### ISSUE TITLE
Issue with android 12

### ISSUE THREAD

**Issue by donaldtrieuit** [livekit/client-sdk-flutter#69]
This is old issue. It was fixed and closed. But it still error in android 12
<img width="1280" alt="Screen Shot 2022-01-08 at 6 59 13 PM" src="https://user-images.githubusercontent.com/65456208/148643349-20bdc4a4-0aa9-491d-bdbe-6153f4a0756d.png">

**Comment by hiroshihorie** [comment]
Hi @donaldtrieuit 
Could you try configuring your livekit server to use `VP8` and observe if the issue persists ?
Edit your server's config file with the following entry :
```yaml
room:
  enabled_codecs:
    - mime: audio/opus
    - mime: video/vp8
```
